#!/bin/bash

# Folder containing the CSVs and YAMLs generated from the original traces used to 
# prepare the nodes' and pods' YAMLs for the various experiments.
INDIR=""

# Based on the selected CSV file, we will generate a trace folder that will be used as input folder for the simulator
file=openb_pod_list_default.csv
echo $file

# Create trace folders with the name of csv trace file (without .csv)
filename="${file##*/}"
OUTDIR="${filename%.*}"
mkdir -p $OUTDIR

# Copy node yaml (generated by openb_node_list_gpu_node.csv) to the trace folder
cp ${INDIR}openb_node_list_gpu_node.yaml $OUTDIR/

# Transform csv file to yaml file and put it under trace folder
python3 pod_csv_to_yaml.py $file

date
